name: virtual_scroll
description: virtual-scroll component for AngularDart
version: 0.1.0
environment:
  sdk: '>=1.24.0 <2.0.0'
dependencies:
  angular: "^4.0.0-alpha+1"
  http: ^0.11.3
  stream_transformers: ^0.3.0
web:
  compiler:
    debug: dartdevc
    release: dart2js
transformers:
- angular:
    entry_points: web/main.dart
    resolved_identifiers:
      BrowserClient: 'package:http/browser_client.dart'
      Client: 'package:http/http.dart'
