name: angular_virtual_scroll
description: Virtual scroll component for Angular
version: 0.1.0
homepage: https://github.com/leftyio/angular_virtual_scroll

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0

dev_dependencies:
  build_runner:
  build_web_compilers:  
  
