name: virtual_scroll
description: virtual-scroll component for AngularDart
version: 0.0.2
environment:
  sdk: '>=1.24.0 <2.0.0'
dependencies:
  angular2: ^3.1.0
  http: ^0.11.3
  stream_transformers: ^0.3.0
web:
  compiler:
    debug: dartdevc
    release: dart2js
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
    resolved_identifiers:
      BrowserClient: 'package:http/browser_client.dart'
      Client: 'package:http/http.dart'
